{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hjl.tcunative",
    "module": "tcunative",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "tcunative-1.0.0.jar",
          "url": "tcunative-1.0.0.jar",
          "size": 14202,
          "sha512": "9c9422e268cc15d4b115f378285decdefbb88a3789e0ca8a9a30a805514f2680edd4c22ce3864f57ce3777f94ad00a23526ca942584f05647ef118447e59af70",
          "sha256": "22f63320b00dc7b9e89e5e4442442380c197aa889560f3f782f39469a0d538b8",
          "sha1": "1d4749e4f567cb9996a80104891c72889990a39b",
          "md5": "9fa151bae95c056929053f23b5dca553"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tcunative-1.0.0.jar",
          "url": "tcunative-1.0.0.jar",
          "size": 14202,
          "sha512": "9c9422e268cc15d4b115f378285decdefbb88a3789e0ca8a9a30a805514f2680edd4c22ce3864f57ce3777f94ad00a23526ca942584f05647ef118447e59af70",
          "sha256": "22f63320b00dc7b9e89e5e4442442380c197aa889560f3f782f39469a0d538b8",
          "sha1": "1d4749e4f567cb9996a80104891c72889990a39b",
          "md5": "9fa151bae95c056929053f23b5dca553"
        }
      ]
    }
  ]
}
