{
  "formatVersion": "1.1",
  "component": {
    "group": "com.yanzhenjie.andserver",
    "module": "annotation",
    "version": "5.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kctrnc3ygfaizh3e4uwrgvgnre"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "annotation-5.0.0.jar",
          "url": "annotation-5.0.0.jar",
          "size": 14077,
          "sha512": "21ff6e5342c66392f0d87d2dd90b8017eb98ddec5d39785bc1d0fbfd7a68e8b519f5f533ae9c800b3706d1e8526023c4f78a333b6ec60a5696b3c66d50aaefcc",
          "sha256": "a443b7c5fc8303dc03a4925fd022cc062991b447ffd83310c1f3052ecbb0e6c4",
          "sha1": "f6f8a5c821c59200e1aedbe715870654d325df5a",
          "md5": "9b66fc741204a6c4173e76d767bc1116"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotation-5.0.0.jar",
          "url": "annotation-5.0.0.jar",
          "size": 14077,
          "sha512": "21ff6e5342c66392f0d87d2dd90b8017eb98ddec5d39785bc1d0fbfd7a68e8b519f5f533ae9c800b3706d1e8526023c4f78a333b6ec60a5696b3c66d50aaefcc",
          "sha256": "a443b7c5fc8303dc03a4925fd022cc062991b447ffd83310c1f3052ecbb0e6c4",
          "sha1": "f6f8a5c821c59200e1aedbe715870654d325df5a",
          "md5": "9b66fc741204a6c4173e76d767bc1116"
        }
      ]
    }
  ]
}
